//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolarisCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PolarisCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not
        ///also
        ///very
        ///often
        ///however
        ///too
        ///usually
        ///really
        ///early
        ///never
        ///always
        ///sometimes
        ///together
        ///likely
        ///simply
        ///generally
        ///instead
        ///actually
        ///again
        ///rather
        ///almost
        ///especially
        ///ever
        ///quickly
        ///probably
        ///already
        ///below
        ///directly
        ///therefore
        ///else
        ///thus
        ///easily
        ///eventually
        ///exactly
        ///certainly
        ///normally
        ///currently
        ///extremely
        ///finally
        ///constantly
        ///properly
        ///soon
        ///specifically
        ///ahead
        ///daily
        ///highly
        ///immediately
        ///relatively
        ///slowly
        ///fairly
        ///primarily
        ///completely
        ///ultimately
        ///widely
        ///recently
        ///seriously
        ///frequently
        ///fully
        ///mostly
        ///naturally
        ///nearly
        ///occasionally
        ///carefully
        ///c [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Adverbs {
            get {
                return ResourceManager.GetString("Adverbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to polaris
        ///please
        ///about.
        /// </summary>
        public static string Ignored_Words {
            get {
                return ResourceManager.GetString("Ignored_Words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how
        ///what
        ///where
        ///which
        ///who
        ///whose
        ///whom
        ///whatever
        ///whatsoever
        ///whichever
        ///whoever
        ///whosoever
        ///whomever
        ///whomsoever
        ///whosever
        ///why
        ///whence
        ///whether
        ///whither
        ///whatsoever.
        /// </summary>
        public static string Interrogative_Words {
            get {
                return ResourceManager.GetString("Interrogative_Words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to polaris
        ///people
        ///history
        ///way
        ///art
        ///world
        ///information
        ///map
        ///two
        ///family
        ///government
        ///health
        ///system
        ///computer
        ///meat
        ///year
        ///thanks
        ///music
        ///person
        ///reading
        ///method
        ///data
        ///food
        ///understanding
        ///theory
        ///law
        ///bird
        ///literature
        ///problem
        ///software
        ///control
        ///knowledge
        ///power
        ///ability
        ///economics
        ///love
        ///internet
        ///television
        ///science
        ///library
        ///nature
        ///fact
        ///product
        ///idea
        ///temperature
        ///investment
        ///area
        ///society
        ///activity
        ///story
        ///industry
        ///media
        ///thing
        ///oven
        ///community
        ///definition
        ///safety
        ///quality
        ///development
        ///language
        ///management
        ///player
        ///variety
        ///video
        ///week
        ///security
        ///country
        ///exam
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Nouns {
            get {
                return ResourceManager.GetString("Nouns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i
        ///me
        ///my
        ///mine
        ///myself
        ///you
        ///you
        ///your
        ///yours
        ///yourself
        ///he
        ///him
        ///his
        ///his
        ///himself
        ///she
        ///her
        ///her
        ///hers
        ///herself
        ///it
        ///it
        ///its
        ///itself
        ///we
        ///us
        ///our
        ///ours
        ///ourselves
        ///you
        ///you
        ///your
        ///yours
        ///yourselves
        ///they
        ///them
        ///their
        ///theirs
        ///themselves.
        /// </summary>
        public static string Pronouns {
            get {
                return ResourceManager.GetString("Pronouns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,
        ///.
        ///?
        ///!
        ///;.
        /// </summary>
        public static string Punctuation_Marks {
            get {
                return ResourceManager.GetString("Punctuation_Marks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add
        ///calculate
        ///call
        ///change
        ///clear
        ///command
        ///connect
        ///copy
        ///debug
        ///enter
        ///entertain
        ///expand
        ///found
        ///inform
        ///open
        ///pause
        ///phone
        ///record
        ///release
        ///remember
        ///remind
        ///remove
        ///reply
        ///search
        ///send
        ///stop
        ///store
        ///talk
        ///test
        ///turn.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accept
        ///add
        ///admire
        ///admit
        ///advise
        ///afford
        ///agree
        ///alert
        ///allow
        ///amuse
        ///analyse
        ///analyze
        ///announce
        ///annoy
        ///answer
        ///apologise
        ///appear
        ///applaud
        ///appreciate
        ///approve
        ///are
        ///argue
        ///arrange
        ///arrest
        ///arrive
        ///ask
        ///attach
        ///attack
        ///attempt
        ///attend
        ///attract
        ///avoid
        ///back
        ///bake
        ///balance
        ///ban
        ///bang
        ///bare
        ///bat
        ///bathe
        ///battle
        ///beam
        ///beg
        ///behave
        ///belong
        ///bleach
        ///bless
        ///blind
        ///blink
        ///blot
        ///blush
        ///boast
        ///boil
        ///bolt
        ///bomb
        ///book
        ///bore
        ///borrow
        ///bounce
        ///bow
        ///box
        ///brake
        ///branch
        ///breathe
        ///bruise
        ///brush
        ///bubble
        ///bump
        ///burn
        ///bury
        ///buzz
        ///calculate
        ///call
        ///camp
        ///can
        ///care
        ///carry
        ///carve
        ///cause
        ///challenge
        ///change
        ///cha [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Verbs {
            get {
                return ResourceManager.GetString("Verbs", resourceCulture);
            }
        }
    }
}
